### ISSUE TITLE
Weißes Dauerleuchten nach ca. 4 Tagen, Webinterface nicht mehr erreichbar

### ISSUE THREAD

**Issue by ADoebeling** [fabian727/EasyRGB#1]
Nach ca. 4 Tagen am Strom schaltet sich die Leiste selbstständig auf weißes Dauerleuchten, das Webinterface ist dann nicht mehr erreichbar. Ich vermute Du hast hier irgendwo einen Speicherüberlauf drin?

**Comment by fabian727** [comment]
sollte hiermit gelöst sein: cd467fe6b8cc138cf1067a73e781e237da1e98ad
